export enum ActionTypes {
  FETCH_USER_PROFILE_DATA = '[User Profile] FETCH_USER_PROFILE_DATA',
  FETCH_USER_PROFILE_DATA_SUCCESS = '[User Profile] FETCH_USER_PROFILE_DATA_SUCCESS',
  FETCH_USER_PROFILE_DATA_FAILURE = '[User Profile] FETCH_USER_PROFILE_DATA_FAILURE'
}
