export enum ProfileUserActionTypes {
  FETCH_PROFILE_USER = 'PROFILE_USER/FETCH_PROFILE_USER',
  FETCH_PROFILE_USER_SUCCESS = 'PROFILE_USER/FETCH_PROFILE_USER_SUCCESS',
  FETCH_PROFILE_USER_FAILURE = 'PROFILE_USER/FETCH_PROFILE_USER_FAILURE',
}
