export enum UserRepositoriesActionTypes {
  FETCH_USER_REPOSITORIES = 'PROFILE_USER/FETCH_USER_REPOSITORIES',
  FETCH_USER_REPOSITORIES_SUCCESS = 'PROFILE_USER/FETCH_USER_REPOSITORIES_SUCCESS',
  FETCH_USER_REPOSITORIES_FAILURE = 'PROFILE_USER/FETCH_USER_REPOSITORIES_FAILURE',
}
